import { Party } from './Party';
import { PaymentDisbursementDetails } from '../../common/entities/PaymentDisbursementDetails';
import { Time } from '@angular/common';

export class CasePayment {

  paymentOID: number = 0; //generated by the system
  caseOID: number = 0; //
  caseNumber: string = "";
  courtOID: number = 0;

  receiptNumber: string = "";
  partyFullName: string = "Rhea Loni Fardey";
  
  payorOID: number = 0;
  beneficiaryOID: number = 0;

  
  dateOfPayment: Date = null; //date the payment was actually made and not entered into the system.
  disbursementDate: Date = null; //receiver from the server after a payment is done
  
  payorParty: Party = new Party(); //This will be retrieved from the server
  beneficiaryParty: Party = new Party(); //This will be retrieved from the server
  staffPartyRecordingPayment: Party = new Party(); //This will be retrieved from the server
  staffPartyRecordingDisbursement: Party = new Party(); //This is to be used for the update of a record

  paymentMethod: string = "";
  paymentType: string = "";
  processingFee: number = 0;
  totalPaymentIn: number = 0;
  totalPaymentOut: number = 0;

  paymentDisbursedFlag = 0;

  paymentsDisbursements: PaymentDisbursementDetails [] = [];


}
